app:
  name: "web_app"
  mode: "dev"
  port: 8081
  version: 0.0.0
  machine_id: 1
  start_time: "2023-01-01"

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 300
  max_backup: 7
mysql:
  host: "localhost"
  port: 3306
  user: "root"
  password: "root1234"
  dbname: "gin"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: "127.0.0.1"
  port: 16379
  db: 0
  password: ""
  pool_size: 100